version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www/
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    ports:
      - 8080:80
    # links:
    #   - db:db
  # The Database
  db:
    image: mysql:5.6
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=chi_con_tiec_nuoi_nhung_mua_nho"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=admin"
      - "MYSQL_ROOT_PASSWORD=admin"
    ports:
        - "3306:3306"
  
volumes:
  dbdata:
