version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:

### Workspace Utilities ##################################
    workspace:
      container_name: laravel-tech-workspace
      build:
        context: ./workspace
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - LARADOCK_PHALCON_VERSION=${PHALCON_VERSION}
          - INSTALL_SYMFONY=${WORKSPACE_INSTALL_SYMFONY}
          - INSTALL_IMAGE_OPTIMIZERS=${WORKSPACE_INSTALL_IMAGE_OPTIMIZERS}
          - INSTALL_IMAGEMAGICK=${WORKSPACE_INSTALL_IMAGEMAGICK}
          - INSTALL_PHALCON=${WORKSPACE_INSTALL_PHALCON}
          - INSTALL_MYSQL_CLIENT=${WORKSPACE_INSTALL_MYSQL_CLIENT}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      ports:
        - "${WORKSPACE_SSH_PORT}:22"
      tty: true
      environment:
        - DOCKER_HOST=tcp://docker-in-docker:2375
      networks:
        - backend
      links:
        - docker-in-docker

### PHP-FPM ##############################################
    php-fpm:
      container_name: laravel-tech-php-fpm
      build:
        context: ./php-fpm
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - LARADOCK_PHALCON_VERSION=${PHALCON_VERSION}
          - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2375
      depends_on:
        - workspace
      networks:
        - backend
      links:
        - docker-in-docker

### NGINX Server #########################################
    nginx:
      container_name: laravel-tech-nginx
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - CHANGE_SOURCE=${CHANGE_SOURCE}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - backend

  ### MySQL ################################################
#    mysql:
#      container_name: laravel-tech-database
#      build:
#        context: ./mysql
#        args:
#          - MYSQL_VERSION=${MYSQL_VERSION}
##      environment:
##        - MYSQL_DATABASE=${MYSQL_DATABASE}
##        - MYSQL_USER=${MYSQL_USER}
##        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
##        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      environment:
#        - "MYSQL_DATABASE=goodgame"
#        - "MYSQL_USER=admin"
#        - "MYSQL_PASSWORD=admin"
#        - "MYSQL_ROOT_PASSWORD=admin"
#      volumes:
#        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
#        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
#      ports:
#        - "${MYSQL_PORT}:3306"
#      networks:
#        - backend

    mysql:
      container_name: laravel-tech-database
      image: mysql:5.6
      volumes:
        - ./dbdata:/var/lib/mysql
      environment:
        - "MYSQL_DATABASE=goodgame"
        - "MYSQL_USER=admin"
        - "MYSQL_PASSWORD=admin"
        - "MYSQL_ROOT_PASSWORD=admin"
      ports:
        - "3306:3306"
      networks:
        - backend

  ### Docker-in-Docker ################################################
    docker-in-docker:
      container_name: laravel-tech-dind
      image: docker:dind
      privileged: true
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      expose:
        - 2375
      networks:
        - backend
